### ISSUE TITLE
Why check that window and Node exist globally?

### ISSUE THREAD

**Issue by stevenvachon** [npm-dom/is-dom#10]
In a jsdom scenario, those globals are not defined by default and could return `false` for a perfectly fine `Node`.

**Comment by TehShrike** [comment]
I'm only particularly interested in supporting browser environments – but this is confused by the fact that right now the automated tests only run this in jsdom.

**Comment by stevenvachon** [comment]
I think that this library can be *simplified* to also support a server/jsdom environment, though.

**Comment by TehShrike** [comment]
Those environments don't have true [Node](https://developer.mozilla.org/en-US/docs/Web/API/Node)s though

**Comment by stevenvachon** [comment]
`window` can be faked just as easily as a `Node` is, so it doesn't assert any more trueness.

**Comment by stevenvachon** [comment]
@TehShrike more thoughts? I think we should support JSDOM Nodes.

**Comment by TehShrike** [comment]
But then this module would lie, and would return `true` in cases where it wasn't passed a DOM node.

If you want to publish a package `looks-like-dom`, copy the lines you want out of https://github.com/npm-dom/is-dom/blob/master/index.js

Probably something like

```js
const isObject = require(`is-object`)

function looksLikeDom(val) {
	return isObject(val)
		&& typeof val.nodeType === `number`
		&& typeof val.nodeName === `string`
}
```

**Comment by TehShrike** [comment]
actually, what makes you think that the current code doesn't work on jsdom nodes?  The code hasn't changed meaningfully since #9 when the tests were passing with jsdom

**Comment by TehShrike** [comment]
Also, you're the one who made the code change in #9 that made it rely on the global `window` 0_o

**Comment by stevenvachon** [comment]
I didn't add the logic, I just updated it from `typeof window === 'object'`.

The current code does work on jsdom nodes, but only if you `global.window = new JSDOM(…).window`. My argument, though, is that jsdom nodes are not real nodes, and having the `window` check does not make it any more, but it does make it more difficult to work with.

**Comment by stevenvachon** [comment]
...

**Comment by TehShrike** [comment]
👍

**Comment by stevenvachon** [comment]
I didn't mean close it.

**Comment by stevenvachon** [comment]
I'll ultimately have to replace this lib with "is-dom-fns", which isn't ideal. NPM has enough redundancy already.

**Comment by TehShrike** [comment]
Is there an unanswered question here?  Per https://github.com/npm-dom/is-dom/issues/10#issuecomment-510312726 I think the answer is "because this module should only return `true` when passed a DOM Node"

**Comment by stevenvachon** [comment]
But a jsDOM node _is_ a DOM node.

**Comment by TehShrike** [comment]
No, it's a JS object that emulates a [DOM node](https://developer.mozilla.org/en-US/docs/Web/API/Node)

**Comment by stevenvachon** [comment]
The [DOM](https://dom.spec.whatwg.org/) is a standard, to which jsdom is a JavaScript-based implementation of it, with the exception of a renderer.

**Comment by stevenvachon** [comment]
[dom-predicates](https://github.com/stevenvachon/dom-predicates)
