### ISSUE TITLE
Copyright information.

### ISSUE THREAD

**Issue by CidFer** [npm-dom/is-dom#13]
The license does not have the copyright information and I was not able to find the author information anywhere. Could you please include it? Thanks.

**Comment by TehShrike** [comment]
The package is licensed MIT https://github.com/npm-dom/is-dom/blob/master/package.json#L17

**Comment by CidFer** [comment]
Hi Josh,

Thanks for answering me back. Yes, I saw the license, but it does not have
the copyright info on it. Also I was not able to find who the author is.
Would you be able to help me with that?

Thanks!

**Comment by TehShrike** [comment]
What do you mean by "copyright info"?  What do you need besides the license that the code has been released under?

The authors can be found here: https://github.com/npm-dom/is-dom/graphs/contributors

**Comment by CidFer** [comment]
Usually the license brings the name of who created the code, so this is the
info I need.

**Comment by TehShrike** [comment]
The initial commits were by @yoshuawuyts so I'd say you could use his name.

**Comment by CidFer** [comment]
Perfect. Thanks Josh!!

**Comment by TehShrike** [comment]
👍
