### ISSUE TITLE
Utilities library?

### ISSUE THREAD

**Issue by stevenvachon** [npm-dom/is-dom#14]
Would you be open to the idea of converting this into a multi-function library, similar to [date-fns](https://npmjs.com/date-fns)?:

```js
import {
  isDetachedDOMNode,
  isDocumentDOMElement,
  isDOMElement,
  isDOMNode,
  isVoidDOMElement
} from 'is-dom';
```

I have these published separately already, but the use of many of them bloats a project's _package.json_ file. I'd like to move them to this project and unpublish them.

**Comment by TehShrike** [comment]
That seems like a reasonable idea, but it feels like it should be a new package, rather than a new version of this single-purpose package.

**Comment by stevenvachon** [comment]
I think the name is fitting, though, as each function would be `is*`. I think a major version change would be sufficient to avoid issues.

**Comment by TehShrike** [comment]
Maybe `is-dom-fns`?

**Comment by stevenvachon** [comment]
No! 🤪

**Comment by stevenvachon** [comment]
Alright.
