### ISSUE TITLE
Cross-realm support

### ISSUE THREAD

**Issue by stevenvachon** [npm-dom/is-dom#7]
Because you use `instance of Node`, nodes from other documents will return `false`.

**Comment by TehShrike** [comment]
Makes sense.

If you want to open a pull request with a failing test, that would be much appreciated.

The tests in this repo use jsdom, which I'm assuming doesn't allow us to make assertions about this kind of behavior.

It would probably be easiest to use electron via `tape-run` instead, ala https://github.com/npm-dom/youtube-video/blob/master/package.json#L7

**Comment by stevenvachon** [comment]
I'd recommend using puppeteer.

**Comment by TehShrike** [comment]
Sure, if you're willing to set it up, I'd be fine merging that.

**Comment by stevenvachon** [comment]
Continuing with jsdom worked just fine. I just created another JSDOM instance (new pseudo-realm).

**Comment by TehShrike** [comment]
The code has been merged and the version bumped in the package.json, but we need @yoshuawuyts to publish

**Comment by stevenvachon** [comment]
@yoshuawuyts ^^
